---
version: "3.7"
services:

  zoekt-webserver:
    image: x0rzkov/gcse:latest-alpine
    container_name: zoekt-webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 6070:6070
    networks:
    - intranet
    - web
    volumes:
    - zoekt-data:/opt/zoekt/data
    command: ["zoekt-webserver"]

  zoekt-archive-index:
    container_name: zoekt-archive-index
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - zoekt-data:/opt/zoekt/data
    networks:
    - intranet
    command: ["zoekt-archive-index"]

volumes:
    zoekt-data:

networks: 
  intranet:
  web:
    external: true  